- tools/CliResT/common/clients_tests.py
- tools/CliResT/common/vars.py
- tools/CliResT/dump_to_es.py
- tools/CliResT/quick_log_analyzer.py
- tools/CliResT/run.sh
- tools/CliResT/run_tests.py
Adding tools with the Upload/Download testing tool.
> tools: Client and Resources Tests

- common/check_sync_rses_with_agis
> Protocols: adding storm to agis collector - #2545

- common/check_rse_attributes
not needed anymore, and was with wrong 1/0/true/false handling anyway
> remove ALL attribute

- common/check_lost_files
- common/import_cric.py
multiple changes:
-   e-mail view improvements (text/html alternative presentation, attachments are recognized now as text/application),
-   3 types of statistics is counting and displaying in letters,
-   bugs fixes (major: loss of lost files info; time intervals gaps/overlaps),
-   some code refined, test and profiling capabilities were improved
> check_lost_files e-mail view and other improvements

- common/check_expired_dids
- common/check_new_dids
- common/check_updated_dids
Supercedes #27 
What do you think @dchristidis ?
> Generalize a few probes and make them use SQLAlchemy

- cms/check_rule_counts
@dchristidis here is the CMS specific one. Others coming
> Add first check_rule_contents to CMS

- common/check_injecting_rules
This one is a straightforward conversion
> SQLAlchemy conversion of check_injecting_rules

- common/check_sync_rses_with_agis
Related to: https://github.com/rucio/rucio/issues/1648
> Set the appropriate RSE type

- common/check_expired_rules
@dchristidis here are the minimal changes needed from PR50 to get this working with Rucio 1.27
> Minimal changes related to PR50

- cms/check_report_free_space
Mostly written by Donata. Updated for Rucio 1.27 by Eric
> Add report_free_space probe

- common/import_cric_users.py
This is importing Accounts and Identities from CRIC into Rucio as described here https://docs.google.com/document/d/168WijsTdfmRumkODn8n4eceN8K_Y3hRn0F2ZKxV5cEo/edit#heading=h.ktdgh27wjqsa 
I thought it is better to separate the two operations (Importing RSEs/Matrix entries and Importing Users).
If you think all CRIC related things should go to one file I can take over #17 and port my code there.
> introduces CRIC users probe

- cms/utils.py
- common/check_expired_rules
- common/utils/common.py
This is what remains of PR50 after fixing the immediate issues with the probe
> Add a prefix for prometheus (needed by CMS)

- atlas/check_storage_space
> ATLAS: retire redundant RSEUsage counters #2

- common/check_deletable_replicas
@ericvaandering I believe CMS overwriting this probe, but maybe you would like to review it regardless.
> Adapt check_deletable_replicas

- CONTRIBUTING.md
As agreed in a past [Rucio Development Meeting](https://indico.cern.ch/event/1011022/#6-component-discussion-probes).
> Add a contributor guide #84

- cms/check_rules_states_by_account
> Check rules state probe 2

- common/check_expired_dids
- common/check_fts_backlog
- common/check_messages_to_submit
- common/check_new_dids
- common/check_oracle
- common/check_requests_to_rses
- common/check_stuck_rules
- common/check_transfer_queues_status
- common/check_unevaluated_dids
- common/check_unlocked_replicas
- common/check_updated_dids
Here is giving the common probes the same treatment. These probes are all running in CMS. Fixes #108
> Adapt common probes to new gauge #108

- atlas/check_injecting_rules
- atlas/check_rules
- atlas/check_stresstest_dids_requests_replicas_daily
- atlas/check_stresstest_dids_requests_replicas_hourly
- atlas/utils.py
- common/check_expired_rules
First commit affects the `Common` probes and is a leftover from #113; please review.
> Port probes Rucio 1.30 #108

- atlas/check_set_rse_space_limits
See https://github.com/rucio/rucio/issues/6313
> ATLAS: Retire MaxBeingDeletedFiles RSE limit

- cms/check_expected_total_number_of_files_per_rse
- cms/check_expiring_rules_per_rse
- cms/check_report_used_space
- common/check_expired_rules
- common/utils/common.py
I'll split this up into a number of PRs but this is the starting point
> Common: create and use new context manager for prometheus metrics - fixes #119

- cms/check_rule_counts
Fixes https://github.com/dmwm/CMSRucio/issues/720 
@ericvaandering @Panos512 fyi
> CMS: Make check_rules_count probe values coherent

- atlas/check_injecting_rules
And various other small improvements.
> Port check_injecting_rules to SQLAlchemy 2.0 sytnax

- cms/check_rse_settings_attributes
Related to https://github.com/dmwm/CMSRucio/issues/912
This is a probe that collects numeric and boolean RSE settings and attributes.
It might also be useful for other communities.
FYI @haozturk
> CMS: add probe fetching rses settings and attributes
